//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaymentDbEntities : DbContext
    {
        public PaymentDbEntities()
            : base("name=PaymentDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<DenemeTable> DenemeTable { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Delays> Delays { get; set; }
    }
}
